#:import toast kivymd.toast.toast


<MDDropItem@Screen>
    name: "drop item"

    Toolbar:
        id: toolbar
        pos_hint: {"top": 1}

    MDDropDownItem:
        id: dropdown_item
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        items: [f"Item {i}" for i in range(50)]
        dropdown_bg: [1, 1, 1, 1]

    MDRaisedButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.3}
        text: 'Chek Item'
        on_release: toast(dropdown_item.current_item)
