<Progress@Screen>
    name: 'progress'

    Toolbar:
        id: toolbar
        pos_hint: {"top": 1}

    MDCheckbox:
        id: chkbox
        size_hint: None, None
        size: dp(48), dp(48)
        pos_hint: {'center_x': .5, 'center_y': .4}
        active: True

    MDSpinner:
        id: spinner
        size_hint: None, None
        size: dp(46), dp(46)
        pos_hint: {'center_x': .5, 'center_y': .5}
        active: True if chkbox.active else False