<KitchenSinkRefreshLayout>
    name: "refresh layout"

    BoxLayout:
        orientation: "vertical"
        spacing: "10dp"

        Toolbar:
            id: toolbar

        FloatLayout:

            MDScrollViewRefreshLayout:
                id: refresh_layout
                refresh_callback: root.refresh_callback
                root_layout: root

                MDGridLayout:
                    id: box
                    adaptive_height: True
                    cols: 1
